apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configuration
  name: configuration
  namespace: gantry
spec:
  selector:
    matchLabels:
      app: configuration
  template:
    metadata:
      labels:
        app: configuration
    spec:
      containers:
        - name: configuration
          image: harbor.gantry.ai/gantry/config-management:0.1
          imagePullPolicy: Always
          env:
            - name: AWS_ROUTE53_ACCESSKEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-cred
                  key: route53_accesskey_id
            - name: AWS_ROUTE53_SECRET_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  name: aws-cred
                  key: route53_secret_accesskey
            - name: BASIC_AUTH_ID
              valueFrom:
                secretKeyRef:
                  name: temp-cred
                  key: id
            - name: BASIC_AUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: temp-cred
                  key: password
      imagePullSecrets:
        - name: harbor-cred
